// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: acp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcpMessageKind int32

const (
	AcpMessageKind_HELLO            AcpMessageKind = 0
	AcpMessageKind_HELLO_STATUS     AcpMessageKind = 1
	AcpMessageKind_REQUEST          AcpMessageKind = 2
	AcpMessageKind_DISCOVER_REQUEST AcpMessageKind = 3
	AcpMessageKind_DISCOVER         AcpMessageKind = 4
	AcpMessageKind_READY            AcpMessageKind = 5
	AcpMessageKind_UPDATED          AcpMessageKind = 6
	AcpMessageKind_DELETED          AcpMessageKind = 7
	AcpMessageKind_MANIFEST_REQUEST AcpMessageKind = 8
	AcpMessageKind_MANIFEST         AcpMessageKind = 9
	AcpMessageKind_STATUS_REQUEST   AcpMessageKind = 10
	AcpMessageKind_STATUS           AcpMessageKind = 11
	AcpMessageKind_DELOAD           AcpMessageKind = 12
)

// Enum value maps for AcpMessageKind.
var (
	AcpMessageKind_name = map[int32]string{
		0:  "HELLO",
		1:  "HELLO_STATUS",
		2:  "REQUEST",
		3:  "DISCOVER_REQUEST",
		4:  "DISCOVER",
		5:  "READY",
		6:  "UPDATED",
		7:  "DELETED",
		8:  "MANIFEST_REQUEST",
		9:  "MANIFEST",
		10: "STATUS_REQUEST",
		11: "STATUS",
		12: "DELOAD",
	}
	AcpMessageKind_value = map[string]int32{
		"HELLO":            0,
		"HELLO_STATUS":     1,
		"REQUEST":          2,
		"DISCOVER_REQUEST": 3,
		"DISCOVER":         4,
		"READY":            5,
		"UPDATED":          6,
		"DELETED":          7,
		"MANIFEST_REQUEST": 8,
		"MANIFEST":         9,
		"STATUS_REQUEST":   10,
		"STATUS":           11,
		"DELOAD":           12,
	}
)

func (x AcpMessageKind) Enum() *AcpMessageKind {
	p := new(AcpMessageKind)
	*p = x
	return p
}

func (x AcpMessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcpMessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_acp_proto_enumTypes[0].Descriptor()
}

func (AcpMessageKind) Type() protoreflect.EnumType {
	return &file_acp_proto_enumTypes[0]
}

func (x AcpMessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcpMessageKind.Descriptor instead.
func (AcpMessageKind) EnumDescriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{0}
}

type AcpStatusCode int32

const (
	AcpStatusCode_OK             AcpStatusCode = 0
	AcpStatusCode_NOT_FOUND      AcpStatusCode = 1
	AcpStatusCode_BAD_REQUEST    AcpStatusCode = 2
	AcpStatusCode_INTERNAL_ERROR AcpStatusCode = 3
)

// Enum value maps for AcpStatusCode.
var (
	AcpStatusCode_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "BAD_REQUEST",
		3: "INTERNAL_ERROR",
	}
	AcpStatusCode_value = map[string]int32{
		"OK":             0,
		"NOT_FOUND":      1,
		"BAD_REQUEST":    2,
		"INTERNAL_ERROR": 3,
	}
)

func (x AcpStatusCode) Enum() *AcpStatusCode {
	p := new(AcpStatusCode)
	*p = x
	return p
}

func (x AcpStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcpStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_acp_proto_enumTypes[1].Descriptor()
}

func (AcpStatusCode) Type() protoreflect.EnumType {
	return &file_acp_proto_enumTypes[1]
}

func (x AcpStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcpStatusCode.Descriptor instead.
func (AcpStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{1}
}

type AcpAssetMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CachePath     string                 `protobuf:"bytes,2,opt,name=cache_path,json=cachePath,proto3" json:"cache_path,omitempty"`
	PayloadHash   string                 `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	FileLength    int64                  `protobuf:"varint,4,opt,name=file_length,json=fileLength,proto3" json:"file_length,omitempty"`
	UriVersion    int64                  `protobuf:"varint,5,opt,name=uri_version,json=uriVersion,proto3" json:"uri_version,omitempty"`
	UpdatedAtNs   int64                  `protobuf:"varint,6,opt,name=updated_at_ns,json=updatedAtNs,proto3" json:"updated_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcpAssetMetadata) Reset() {
	*x = AcpAssetMetadata{}
	mi := &file_acp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcpAssetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcpAssetMetadata) ProtoMessage() {}

func (x *AcpAssetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcpAssetMetadata.ProtoReflect.Descriptor instead.
func (*AcpAssetMetadata) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{0}
}

func (x *AcpAssetMetadata) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *AcpAssetMetadata) GetCachePath() string {
	if x != nil {
		return x.CachePath
	}
	return ""
}

func (x *AcpAssetMetadata) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

func (x *AcpAssetMetadata) GetFileLength() int64 {
	if x != nil {
		return x.FileLength
	}
	return 0
}

func (x *AcpAssetMetadata) GetUriVersion() int64 {
	if x != nil {
		return x.UriVersion
	}
	return 0
}

func (x *AcpAssetMetadata) GetUpdatedAtNs() int64 {
	if x != nil {
		return x.UpdatedAtNs
	}
	return 0
}

type AcpMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *uint32                `protobuf:"varint,1,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Kind          AcpMessageKind         `protobuf:"varint,2,opt,name=kind,proto3,enum=acp.AcpMessageKind" json:"kind,omitempty"`
	RequestId     uint64                 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Uri           *string                `protobuf:"bytes,4,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	ForceRecook   *bool                  `protobuf:"varint,5,opt,name=force_recook,json=forceRecook,proto3,oneof" json:"force_recook,omitempty"`
	Uris          []string               `protobuf:"bytes,6,rep,name=uris,proto3" json:"uris,omitempty"`
	Status        *AcpStatusCode         `protobuf:"varint,7,opt,name=status,proto3,enum=acp.AcpStatusCode,oneof" json:"status,omitempty"`
	Detail        *string                `protobuf:"bytes,8,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Metadata      *AcpAssetMetadata      `protobuf:"bytes,9,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,10,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkTotal    uint32                 `protobuf:"varint,11,opt,name=chunk_total,json=chunkTotal,proto3" json:"chunk_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcpMessage) Reset() {
	*x = AcpMessage{}
	mi := &file_acp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcpMessage) ProtoMessage() {}

func (x *AcpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_acp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcpMessage.ProtoReflect.Descriptor instead.
func (*AcpMessage) Descriptor() ([]byte, []int) {
	return file_acp_proto_rawDescGZIP(), []int{1}
}

func (x *AcpMessage) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *AcpMessage) GetKind() AcpMessageKind {
	if x != nil {
		return x.Kind
	}
	return AcpMessageKind_HELLO
}

func (x *AcpMessage) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AcpMessage) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *AcpMessage) GetForceRecook() bool {
	if x != nil && x.ForceRecook != nil {
		return *x.ForceRecook
	}
	return false
}

func (x *AcpMessage) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *AcpMessage) GetStatus() AcpStatusCode {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return AcpStatusCode_OK
}

func (x *AcpMessage) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *AcpMessage) GetMetadata() *AcpAssetMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AcpMessage) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *AcpMessage) GetChunkTotal() uint32 {
	if x != nil {
		return x.ChunkTotal
	}
	return 0
}

var File_acp_proto protoreflect.FileDescriptor

const file_acp_proto_rawDesc = "" +
	"\n" +
	"\tacp.proto\x12\x03acp\"\xcc\x01\n" +
	"\x10AcpAssetMetadata\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"cache_path\x18\x02 \x01(\tR\tcachePath\x12!\n" +
	"\fpayload_hash\x18\x03 \x01(\tR\vpayloadHash\x12\x1f\n" +
	"\vfile_length\x18\x04 \x01(\x03R\n" +
	"fileLength\x12\x1f\n" +
	"\vuri_version\x18\x05 \x01(\x03R\n" +
	"uriVersion\x12\"\n" +
	"\rupdated_at_ns\x18\x06 \x01(\x03R\vupdatedAtNs\"\xd6\x03\n" +
	"\n" +
	"AcpMessage\x12\x1d\n" +
	"\aversion\x18\x01 \x01(\rH\x00R\aversion\x88\x01\x01\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.acp.AcpMessageKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId\x12\x15\n" +
	"\x03uri\x18\x04 \x01(\tH\x01R\x03uri\x88\x01\x01\x12&\n" +
	"\fforce_recook\x18\x05 \x01(\bH\x02R\vforceRecook\x88\x01\x01\x12\x12\n" +
	"\x04uris\x18\x06 \x03(\tR\x04uris\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x12.acp.AcpStatusCodeH\x03R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06detail\x18\b \x01(\tH\x04R\x06detail\x88\x01\x01\x126\n" +
	"\bmetadata\x18\t \x01(\v2\x15.acp.AcpAssetMetadataH\x05R\bmetadata\x88\x01\x01\x12\x1f\n" +
	"\vchunk_index\x18\n" +
	" \x01(\rR\n" +
	"chunkIndex\x12\x1f\n" +
	"\vchunk_total\x18\v \x01(\rR\n" +
	"chunkTotalB\n" +
	"\n" +
	"\b_versionB\x06\n" +
	"\x04_uriB\x0f\n" +
	"\r_force_recookB\t\n" +
	"\a_statusB\t\n" +
	"\a_detailB\v\n" +
	"\t_metadata*\xd3\x01\n" +
	"\x0eAcpMessageKind\x12\t\n" +
	"\x05HELLO\x10\x00\x12\x10\n" +
	"\fHELLO_STATUS\x10\x01\x12\v\n" +
	"\aREQUEST\x10\x02\x12\x14\n" +
	"\x10DISCOVER_REQUEST\x10\x03\x12\f\n" +
	"\bDISCOVER\x10\x04\x12\t\n" +
	"\x05READY\x10\x05\x12\v\n" +
	"\aUPDATED\x10\x06\x12\v\n" +
	"\aDELETED\x10\a\x12\x14\n" +
	"\x10MANIFEST_REQUEST\x10\b\x12\f\n" +
	"\bMANIFEST\x10\t\x12\x12\n" +
	"\x0eSTATUS_REQUEST\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06STATUS\x10\v\x12\n" +
	"\n" +
	"\x06DELOAD\x10\f*K\n" +
	"\rAcpStatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x02\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x03b\x06proto3"

var (
	file_acp_proto_rawDescOnce sync.Once
	file_acp_proto_rawDescData []byte
)

func file_acp_proto_rawDescGZIP() []byte {
	file_acp_proto_rawDescOnce.Do(func() {
		file_acp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acp_proto_rawDesc), len(file_acp_proto_rawDesc)))
	})
	return file_acp_proto_rawDescData
}

var file_acp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_acp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acp_proto_goTypes = []any{
	(AcpMessageKind)(0),      // 0: acp.AcpMessageKind
	(AcpStatusCode)(0),       // 1: acp.AcpStatusCode
	(*AcpAssetMetadata)(nil), // 2: acp.AcpAssetMetadata
	(*AcpMessage)(nil),       // 3: acp.AcpMessage
}
var file_acp_proto_depIdxs = []int32{
	0, // 0: acp.AcpMessage.kind:type_name -> acp.AcpMessageKind
	1, // 1: acp.AcpMessage.status:type_name -> acp.AcpStatusCode
	2, // 2: acp.AcpMessage.metadata:type_name -> acp.AcpAssetMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_acp_proto_init() }
func file_acp_proto_init() {
	if File_acp_proto != nil {
		return
	}
	file_acp_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acp_proto_rawDesc), len(file_acp_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acp_proto_goTypes,
		DependencyIndexes: file_acp_proto_depIdxs,
		EnumInfos:         file_acp_proto_enumTypes,
		MessageInfos:      file_acp_proto_msgTypes,
	}.Build()
	File_acp_proto = out.File
	file_acp_proto_goTypes = nil
	file_acp_proto_depIdxs = nil
}
