// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: default2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultColor int32

const (
	DefaultColor_RED   DefaultColor = 0
	DefaultColor_GREEN DefaultColor = 1
	DefaultColor_BLUE  DefaultColor = 2
)

// Enum value maps for DefaultColor.
var (
	DefaultColor_name = map[int32]string{
		0: "RED",
		1: "GREEN",
		2: "BLUE",
	}
	DefaultColor_value = map[string]int32{
		"RED":   0,
		"GREEN": 1,
		"BLUE":  2,
	}
)

func (x DefaultColor) Enum() *DefaultColor {
	p := new(DefaultColor)
	*p = x
	return p
}

func (x DefaultColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultColor) Descriptor() protoreflect.EnumDescriptor {
	return file_default2_proto_enumTypes[0].Descriptor()
}

func (DefaultColor) Type() protoreflect.EnumType {
	return &file_default2_proto_enumTypes[0]
}

func (x DefaultColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DefaultColor) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DefaultColor(num)
	return nil
}

// Deprecated: Use DefaultColor.Descriptor instead.
func (DefaultColor) EnumDescriptor() ([]byte, []int) {
	return file_default2_proto_rawDescGZIP(), []int{0}
}

type DefaultMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OptInt         *int32                 `protobuf:"varint,1,opt,name=opt_int,json=optInt,def=42" json:"opt_int,omitempty"`
	OptString      *string                `protobuf:"bytes,2,opt,name=opt_string,json=optString,def=hello" json:"opt_string,omitempty"`
	OptBool        *bool                  `protobuf:"varint,3,opt,name=opt_bool,json=optBool,def=1" json:"opt_bool,omitempty"`
	OptFloat       *float32               `protobuf:"fixed32,4,opt,name=opt_float,json=optFloat,def=3.14" json:"opt_float,omitempty"`
	OptDouble      *float64               `protobuf:"fixed64,5,opt,name=opt_double,json=optDouble,def=2.718" json:"opt_double,omitempty"`
	OptBytes       []byte                 `protobuf:"bytes,6,opt,name=opt_bytes,json=optBytes,def=raw" json:"opt_bytes,omitempty"`
	OptColor       *DefaultColor          `protobuf:"varint,7,opt,name=opt_color,json=optColor,enum=DefaultColor,def=1" json:"opt_color,omitempty"`
	ReqWithDefault *int32                 `protobuf:"varint,8,req,name=req_with_default,json=reqWithDefault,def=99" json:"req_with_default,omitempty"`
	OptNoDefault   *int32                 `protobuf:"varint,9,opt,name=opt_no_default,json=optNoDefault" json:"opt_no_default,omitempty"`
	OptSint        *int32                 `protobuf:"zigzag32,10,opt,name=opt_sint,json=optSint,def=-10" json:"opt_sint,omitempty"`
	OptUint64      *uint64                `protobuf:"varint,11,opt,name=opt_uint64,json=optUint64,def=1000000" json:"opt_uint64,omitempty"`
	ReqColor       *DefaultColor          `protobuf:"varint,12,req,name=req_color,json=reqColor,enum=DefaultColor,def=2" json:"req_color,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Default values for DefaultMessage fields.
const (
	Default_DefaultMessage_OptInt         = int32(42)
	Default_DefaultMessage_OptString      = string("hello")
	Default_DefaultMessage_OptBool        = bool(true)
	Default_DefaultMessage_OptFloat       = float32(3.140000104904175)
	Default_DefaultMessage_OptDouble      = float64(2.718)
	Default_DefaultMessage_OptColor       = DefaultColor_GREEN
	Default_DefaultMessage_ReqWithDefault = int32(99)
	Default_DefaultMessage_OptSint        = int32(-10)
	Default_DefaultMessage_OptUint64      = uint64(1000000)
	Default_DefaultMessage_ReqColor       = DefaultColor_BLUE
)

// Default values for DefaultMessage fields.
var (
	Default_DefaultMessage_OptBytes = []byte("raw")
)

func (x *DefaultMessage) Reset() {
	*x = DefaultMessage{}
	mi := &file_default2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultMessage) ProtoMessage() {}

func (x *DefaultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_default2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultMessage.ProtoReflect.Descriptor instead.
func (*DefaultMessage) Descriptor() ([]byte, []int) {
	return file_default2_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultMessage) GetOptInt() int32 {
	if x != nil && x.OptInt != nil {
		return *x.OptInt
	}
	return Default_DefaultMessage_OptInt
}

func (x *DefaultMessage) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return Default_DefaultMessage_OptString
}

func (x *DefaultMessage) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return Default_DefaultMessage_OptBool
}

func (x *DefaultMessage) GetOptFloat() float32 {
	if x != nil && x.OptFloat != nil {
		return *x.OptFloat
	}
	return Default_DefaultMessage_OptFloat
}

func (x *DefaultMessage) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return Default_DefaultMessage_OptDouble
}

func (x *DefaultMessage) GetOptBytes() []byte {
	if x != nil && x.OptBytes != nil {
		return x.OptBytes
	}
	return append([]byte(nil), Default_DefaultMessage_OptBytes...)
}

func (x *DefaultMessage) GetOptColor() DefaultColor {
	if x != nil && x.OptColor != nil {
		return *x.OptColor
	}
	return Default_DefaultMessage_OptColor
}

func (x *DefaultMessage) GetReqWithDefault() int32 {
	if x != nil && x.ReqWithDefault != nil {
		return *x.ReqWithDefault
	}
	return Default_DefaultMessage_ReqWithDefault
}

func (x *DefaultMessage) GetOptNoDefault() int32 {
	if x != nil && x.OptNoDefault != nil {
		return *x.OptNoDefault
	}
	return 0
}

func (x *DefaultMessage) GetOptSint() int32 {
	if x != nil && x.OptSint != nil {
		return *x.OptSint
	}
	return Default_DefaultMessage_OptSint
}

func (x *DefaultMessage) GetOptUint64() uint64 {
	if x != nil && x.OptUint64 != nil {
		return *x.OptUint64
	}
	return Default_DefaultMessage_OptUint64
}

func (x *DefaultMessage) GetReqColor() DefaultColor {
	if x != nil && x.ReqColor != nil {
		return *x.ReqColor
	}
	return Default_DefaultMessage_ReqColor
}

var File_default2_proto protoreflect.FileDescriptor

const file_default2_proto_rawDesc = "" +
	"\n" +
	"\x0edefault2.proto\"\xe0\x03\n" +
	"\x0eDefaultMessage\x12\x1b\n" +
	"\aopt_int\x18\x01 \x01(\x05:\x0242R\x06optInt\x12$\n" +
	"\n" +
	"opt_string\x18\x02 \x01(\t:\x05helloR\toptString\x12\x1f\n" +
	"\bopt_bool\x18\x03 \x01(\b:\x04trueR\aoptBool\x12!\n" +
	"\topt_float\x18\x04 \x01(\x02:\x043.14R\boptFloat\x12$\n" +
	"\n" +
	"opt_double\x18\x05 \x01(\x01:\x052.718R\toptDouble\x12 \n" +
	"\topt_bytes\x18\x06 \x01(\f:\x03rawR\boptBytes\x121\n" +
	"\topt_color\x18\a \x01(\x0e2\r.DefaultColor:\x05GREENR\boptColor\x12,\n" +
	"\x10req_with_default\x18\b \x02(\x05:\x0299R\x0ereqWithDefault\x12$\n" +
	"\x0eopt_no_default\x18\t \x01(\x05R\foptNoDefault\x12\x1e\n" +
	"\bopt_sint\x18\n" +
	" \x01(\x11:\x03-10R\aoptSint\x12&\n" +
	"\n" +
	"opt_uint64\x18\v \x01(\x04:\a1000000R\toptUint64\x120\n" +
	"\treq_color\x18\f \x02(\x0e2\r.DefaultColor:\x04BLUER\breqColor*,\n" +
	"\fDefaultColor\x12\a\n" +
	"\x03RED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x02"

var (
	file_default2_proto_rawDescOnce sync.Once
	file_default2_proto_rawDescData []byte
)

func file_default2_proto_rawDescGZIP() []byte {
	file_default2_proto_rawDescOnce.Do(func() {
		file_default2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_default2_proto_rawDesc), len(file_default2_proto_rawDesc)))
	})
	return file_default2_proto_rawDescData
}

var file_default2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_default2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_default2_proto_goTypes = []any{
	(DefaultColor)(0),      // 0: DefaultColor
	(*DefaultMessage)(nil), // 1: DefaultMessage
}
var file_default2_proto_depIdxs = []int32{
	0, // 0: DefaultMessage.opt_color:type_name -> DefaultColor
	0, // 1: DefaultMessage.req_color:type_name -> DefaultColor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_default2_proto_init() }
func file_default2_proto_init() {
	if File_default2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_default2_proto_rawDesc), len(file_default2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_default2_proto_goTypes,
		DependencyIndexes: file_default2_proto_depIdxs,
		EnumInfos:         file_default2_proto_enumTypes,
		MessageInfos:      file_default2_proto_msgTypes,
	}.Build()
	File_default2_proto = out.File
	file_default2_proto_goTypes = nil
	file_default2_proto_depIdxs = nil
}
