// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: edge3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FNan          float64                `protobuf:"fixed64,1,opt,name=f_nan,json=fNan,proto3" json:"f_nan,omitempty"`
	FPosInf       float64                `protobuf:"fixed64,2,opt,name=f_pos_inf,json=fPosInf,proto3" json:"f_pos_inf,omitempty"`
	FNegInf       float64                `protobuf:"fixed64,3,opt,name=f_neg_inf,json=fNegInf,proto3" json:"f_neg_inf,omitempty"`
	FMaxInt32     int32                  `protobuf:"varint,4,opt,name=f_max_int32,json=fMaxInt32,proto3" json:"f_max_int32,omitempty"`
	FMinInt32     int32                  `protobuf:"varint,5,opt,name=f_min_int32,json=fMinInt32,proto3" json:"f_min_int32,omitempty"`
	FMaxInt64     int64                  `protobuf:"varint,6,opt,name=f_max_int64,json=fMaxInt64,proto3" json:"f_max_int64,omitempty"`
	FMinInt64     int64                  `protobuf:"varint,7,opt,name=f_min_int64,json=fMinInt64,proto3" json:"f_min_int64,omitempty"`
	FMaxUint32    uint32                 `protobuf:"varint,8,opt,name=f_max_uint32,json=fMaxUint32,proto3" json:"f_max_uint32,omitempty"`
	FMaxUint64    uint64                 `protobuf:"varint,9,opt,name=f_max_uint64,json=fMaxUint64,proto3" json:"f_max_uint64,omitempty"`
	FUnicode      string                 `protobuf:"bytes,10,opt,name=f_unicode,json=fUnicode,proto3" json:"f_unicode,omitempty"`
	FBinary       []byte                 `protobuf:"bytes,11,opt,name=f_binary,json=fBinary,proto3" json:"f_binary,omitempty"`
	FEmptyStr     string                 `protobuf:"bytes,12,opt,name=f_empty_str,json=fEmptyStr,proto3" json:"f_empty_str,omitempty"`
	FEmptyBytes   []byte                 `protobuf:"bytes,13,opt,name=f_empty_bytes,json=fEmptyBytes,proto3" json:"f_empty_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeMessage) Reset() {
	*x = EdgeMessage{}
	mi := &file_edge3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMessage) ProtoMessage() {}

func (x *EdgeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_edge3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMessage.ProtoReflect.Descriptor instead.
func (*EdgeMessage) Descriptor() ([]byte, []int) {
	return file_edge3_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeMessage) GetFNan() float64 {
	if x != nil {
		return x.FNan
	}
	return 0
}

func (x *EdgeMessage) GetFPosInf() float64 {
	if x != nil {
		return x.FPosInf
	}
	return 0
}

func (x *EdgeMessage) GetFNegInf() float64 {
	if x != nil {
		return x.FNegInf
	}
	return 0
}

func (x *EdgeMessage) GetFMaxInt32() int32 {
	if x != nil {
		return x.FMaxInt32
	}
	return 0
}

func (x *EdgeMessage) GetFMinInt32() int32 {
	if x != nil {
		return x.FMinInt32
	}
	return 0
}

func (x *EdgeMessage) GetFMaxInt64() int64 {
	if x != nil {
		return x.FMaxInt64
	}
	return 0
}

func (x *EdgeMessage) GetFMinInt64() int64 {
	if x != nil {
		return x.FMinInt64
	}
	return 0
}

func (x *EdgeMessage) GetFMaxUint32() uint32 {
	if x != nil {
		return x.FMaxUint32
	}
	return 0
}

func (x *EdgeMessage) GetFMaxUint64() uint64 {
	if x != nil {
		return x.FMaxUint64
	}
	return 0
}

func (x *EdgeMessage) GetFUnicode() string {
	if x != nil {
		return x.FUnicode
	}
	return ""
}

func (x *EdgeMessage) GetFBinary() []byte {
	if x != nil {
		return x.FBinary
	}
	return nil
}

func (x *EdgeMessage) GetFEmptyStr() string {
	if x != nil {
		return x.FEmptyStr
	}
	return ""
}

func (x *EdgeMessage) GetFEmptyBytes() []byte {
	if x != nil {
		return x.FEmptyBytes
	}
	return nil
}

var File_edge3_proto protoreflect.FileDescriptor

const file_edge3_proto_rawDesc = "" +
	"\n" +
	"\vedge3.proto\"\x9a\x03\n" +
	"\vEdgeMessage\x12\x13\n" +
	"\x05f_nan\x18\x01 \x01(\x01R\x04fNan\x12\x1a\n" +
	"\tf_pos_inf\x18\x02 \x01(\x01R\afPosInf\x12\x1a\n" +
	"\tf_neg_inf\x18\x03 \x01(\x01R\afNegInf\x12\x1e\n" +
	"\vf_max_int32\x18\x04 \x01(\x05R\tfMaxInt32\x12\x1e\n" +
	"\vf_min_int32\x18\x05 \x01(\x05R\tfMinInt32\x12\x1e\n" +
	"\vf_max_int64\x18\x06 \x01(\x03R\tfMaxInt64\x12\x1e\n" +
	"\vf_min_int64\x18\a \x01(\x03R\tfMinInt64\x12 \n" +
	"\ff_max_uint32\x18\b \x01(\rR\n" +
	"fMaxUint32\x12 \n" +
	"\ff_max_uint64\x18\t \x01(\x04R\n" +
	"fMaxUint64\x12\x1b\n" +
	"\tf_unicode\x18\n" +
	" \x01(\tR\bfUnicode\x12\x19\n" +
	"\bf_binary\x18\v \x01(\fR\afBinary\x12\x1e\n" +
	"\vf_empty_str\x18\f \x01(\tR\tfEmptyStr\x12\"\n" +
	"\rf_empty_bytes\x18\r \x01(\fR\vfEmptyBytesb\x06proto3"

var (
	file_edge3_proto_rawDescOnce sync.Once
	file_edge3_proto_rawDescData []byte
)

func file_edge3_proto_rawDescGZIP() []byte {
	file_edge3_proto_rawDescOnce.Do(func() {
		file_edge3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge3_proto_rawDesc), len(file_edge3_proto_rawDesc)))
	})
	return file_edge3_proto_rawDescData
}

var file_edge3_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_edge3_proto_goTypes = []any{
	(*EdgeMessage)(nil), // 0: EdgeMessage
}
var file_edge3_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_edge3_proto_init() }
func file_edge3_proto_init() {
	if File_edge3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge3_proto_rawDesc), len(file_edge3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edge3_proto_goTypes,
		DependencyIndexes: file_edge3_proto_depIdxs,
		MessageInfos:      file_edge3_proto_msgTypes,
	}.Build()
	File_edge3_proto = out.File
	file_edge3_proto_goTypes = nil
	file_edge3_proto_depIdxs = nil
}
