// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: enum3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_RED         Color = 1
	Color_COLOR_GREEN       Color = 2
	Color_COLOR_BLUE        Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_RED",
		2: "COLOR_GREEN",
		3: "COLOR_BLUE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_RED":         1,
		"COLOR_GREEN":       2,
		"COLOR_BLUE":        3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_enum3_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_enum3_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_enum3_proto_rawDescGZIP(), []int{0}
}

type EnumMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         Color                  `protobuf:"varint,1,opt,name=color,proto3,enum=Color" json:"color,omitempty"`
	Colors        []Color                `protobuf:"varint,2,rep,packed,name=colors,proto3,enum=Color" json:"colors,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumMessage) Reset() {
	*x = EnumMessage{}
	mi := &file_enum3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumMessage) ProtoMessage() {}

func (x *EnumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_enum3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumMessage.ProtoReflect.Descriptor instead.
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return file_enum3_proto_rawDescGZIP(), []int{0}
}

func (x *EnumMessage) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *EnumMessage) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *EnumMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_enum3_proto protoreflect.FileDescriptor

const file_enum3_proto_rawDesc = "" +
	"\n" +
	"\venum3.proto\"_\n" +
	"\vEnumMessage\x12\x1c\n" +
	"\x05color\x18\x01 \x01(\x0e2\x06.ColorR\x05color\x12\x1e\n" +
	"\x06colors\x18\x02 \x03(\x0e2\x06.ColorR\x06colors\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name*N\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOLOR_RED\x10\x01\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x02\x12\x0e\n" +
	"\n" +
	"COLOR_BLUE\x10\x03b\x06proto3"

var (
	file_enum3_proto_rawDescOnce sync.Once
	file_enum3_proto_rawDescData []byte
)

func file_enum3_proto_rawDescGZIP() []byte {
	file_enum3_proto_rawDescOnce.Do(func() {
		file_enum3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum3_proto_rawDesc), len(file_enum3_proto_rawDesc)))
	})
	return file_enum3_proto_rawDescData
}

var file_enum3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum3_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enum3_proto_goTypes = []any{
	(Color)(0),          // 0: Color
	(*EnumMessage)(nil), // 1: EnumMessage
}
var file_enum3_proto_depIdxs = []int32{
	0, // 0: EnumMessage.color:type_name -> Color
	0, // 1: EnumMessage.colors:type_name -> Color
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_enum3_proto_init() }
func file_enum3_proto_init() {
	if File_enum3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum3_proto_rawDesc), len(file_enum3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum3_proto_goTypes,
		DependencyIndexes: file_enum3_proto_depIdxs,
		EnumInfos:         file_enum3_proto_enumTypes,
		MessageInfos:      file_enum3_proto_msgTypes,
	}.Build()
	File_enum3_proto = out.File
	file_enum3_proto_goTypes = nil
	file_enum3_proto_depIdxs = nil
}
