// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: extension2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtBase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtBase) Reset() {
	*x = ExtBase{}
	mi := &file_extension2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtBase) ProtoMessage() {}

func (x *ExtBase) ProtoReflect() protoreflect.Message {
	mi := &file_extension2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtBase.ProtoReflect.Descriptor instead.
func (*ExtBase) Descriptor() ([]byte, []int) {
	return file_extension2_proto_rawDescGZIP(), []int{0}
}

func (x *ExtBase) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ExtBase) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var file_extension2_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*ExtBase)(nil),
		ExtensionType: (*int32)(nil),
		Field:         100,
		Name:          "ext_value",
		Tag:           "varint,100,opt,name=ext_value",
		Filename:      "extension2.proto",
	},
	{
		ExtendedType:  (*ExtBase)(nil),
		ExtensionType: (*string)(nil),
		Field:         101,
		Name:          "ext_label",
		Tag:           "bytes,101,opt,name=ext_label",
		Filename:      "extension2.proto",
	},
	{
		ExtendedType:  (*ExtBase)(nil),
		ExtensionType: (*bool)(nil),
		Field:         102,
		Name:          "ext_flag",
		Tag:           "varint,102,opt,name=ext_flag",
		Filename:      "extension2.proto",
	},
}

// Extension fields to ExtBase.
var (
	// optional int32 ext_value = 100;
	E_ExtValue = &file_extension2_proto_extTypes[0]
	// optional string ext_label = 101;
	E_ExtLabel = &file_extension2_proto_extTypes[1]
	// optional bool ext_flag = 102;
	E_ExtFlag = &file_extension2_proto_extTypes[2]
)

var File_extension2_proto protoreflect.FileDescriptor

const file_extension2_proto_rawDesc = "" +
	"\n" +
	"\x10extension2.proto\"4\n" +
	"\aExtBase\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*\x05\bd\x10\xc8\x01:%\n" +
	"\text_value\x12\b.ExtBase\x18d \x01(\x05R\bextValue:%\n" +
	"\text_label\x12\b.ExtBase\x18e \x01(\tR\bextLabel:#\n" +
	"\bext_flag\x12\b.ExtBase\x18f \x01(\bR\aextFlag"

var (
	file_extension2_proto_rawDescOnce sync.Once
	file_extension2_proto_rawDescData []byte
)

func file_extension2_proto_rawDescGZIP() []byte {
	file_extension2_proto_rawDescOnce.Do(func() {
		file_extension2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension2_proto_rawDesc), len(file_extension2_proto_rawDesc)))
	})
	return file_extension2_proto_rawDescData
}

var file_extension2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extension2_proto_goTypes = []any{
	(*ExtBase)(nil), // 0: ExtBase
}
var file_extension2_proto_depIdxs = []int32{
	0, // 0: ext_value:extendee -> ExtBase
	0, // 1: ext_label:extendee -> ExtBase
	0, // 2: ext_flag:extendee -> ExtBase
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extension2_proto_init() }
func file_extension2_proto_init() {
	if File_extension2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension2_proto_rawDesc), len(file_extension2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_extension2_proto_goTypes,
		DependencyIndexes: file_extension2_proto_depIdxs,
		MessageInfos:      file_extension2_proto_msgTypes,
		ExtensionInfos:    file_extension2_proto_extTypes,
	}.Build()
	File_extension2_proto = out.File
	file_extension2_proto_goTypes = nil
	file_extension2_proto_depIdxs = nil
}
