// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: group2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mygroup       *GroupMessage_MyGroup  `protobuf:"group,1,opt,name=MyGroup,json=mygroup" json:"mygroup,omitempty"`
	AfterGroup    *int32                 `protobuf:"varint,4,opt,name=after_group,json=afterGroup" json:"after_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	mi := &file_group2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_group2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_group2_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMessage) GetMygroup() *GroupMessage_MyGroup {
	if x != nil {
		return x.Mygroup
	}
	return nil
}

func (x *GroupMessage) GetAfterGroup() int32 {
	if x != nil && x.AfterGroup != nil {
		return *x.AfterGroup
	}
	return 0
}

type GroupMessage_MyGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Label         *string                `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage_MyGroup) Reset() {
	*x = GroupMessage_MyGroup{}
	mi := &file_group2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage_MyGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage_MyGroup) ProtoMessage() {}

func (x *GroupMessage_MyGroup) ProtoReflect() protoreflect.Message {
	mi := &file_group2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage_MyGroup.ProtoReflect.Descriptor instead.
func (*GroupMessage_MyGroup) Descriptor() ([]byte, []int) {
	return file_group2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GroupMessage_MyGroup) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *GroupMessage_MyGroup) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

var File_group2_proto protoreflect.FileDescriptor

const file_group2_proto_rawDesc = "" +
	"\n" +
	"\fgroup2.proto\"\x97\x01\n" +
	"\fGroupMessage\x12/\n" +
	"\amygroup\x18\x01 \x01(\n" +
	"2\x15.GroupMessage.MyGroupR\amygroup\x12\x1f\n" +
	"\vafter_group\x18\x04 \x01(\x05R\n" +
	"afterGroup\x1a5\n" +
	"\aMyGroup\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label"

var (
	file_group2_proto_rawDescOnce sync.Once
	file_group2_proto_rawDescData []byte
)

func file_group2_proto_rawDescGZIP() []byte {
	file_group2_proto_rawDescOnce.Do(func() {
		file_group2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group2_proto_rawDesc), len(file_group2_proto_rawDesc)))
	})
	return file_group2_proto_rawDescData
}

var file_group2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_group2_proto_goTypes = []any{
	(*GroupMessage)(nil),         // 0: GroupMessage
	(*GroupMessage_MyGroup)(nil), // 1: GroupMessage.MyGroup
}
var file_group2_proto_depIdxs = []int32{
	1, // 0: GroupMessage.mygroup:type_name -> GroupMessage.MyGroup
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_group2_proto_init() }
func file_group2_proto_init() {
	if File_group2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group2_proto_rawDesc), len(file_group2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group2_proto_goTypes,
		DependencyIndexes: file_group2_proto_depIdxs,
		MessageInfos:      file_group2_proto_msgTypes,
	}.Build()
	File_group2_proto = out.File
	file_group2_proto_goTypes = nil
	file_group2_proto_depIdxs = nil
}
