// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: map3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapSubMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSubMsg) Reset() {
	*x = MapSubMsg{}
	mi := &file_map3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSubMsg) ProtoMessage() {}

func (x *MapSubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_map3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSubMsg.ProtoReflect.Descriptor instead.
func (*MapSubMsg) Descriptor() ([]byte, []int) {
	return file_map3_proto_rawDescGZIP(), []int{0}
}

func (x *MapSubMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapSubMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MapMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrStr        map[string]string      `protobuf:"bytes,1,rep,name=str_str,json=strStr,proto3" json:"str_str,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntStr        map[int32]string       `protobuf:"bytes,2,rep,name=int_str,json=intStr,proto3" json:"int_str,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StrMsg        map[string]*MapSubMsg  `protobuf:"bytes,3,rep,name=str_msg,json=strMsg,proto3" json:"str_msg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapMessage) Reset() {
	*x = MapMessage{}
	mi := &file_map3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMessage) ProtoMessage() {}

func (x *MapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_map3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMessage.ProtoReflect.Descriptor instead.
func (*MapMessage) Descriptor() ([]byte, []int) {
	return file_map3_proto_rawDescGZIP(), []int{1}
}

func (x *MapMessage) GetStrStr() map[string]string {
	if x != nil {
		return x.StrStr
	}
	return nil
}

func (x *MapMessage) GetIntStr() map[int32]string {
	if x != nil {
		return x.IntStr
	}
	return nil
}

func (x *MapMessage) GetStrMsg() map[string]*MapSubMsg {
	if x != nil {
		return x.StrMsg
	}
	return nil
}

var File_map3_proto protoreflect.FileDescriptor

const file_map3_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"map3.proto\"/\n" +
	"\tMapSubMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xdf\x02\n" +
	"\n" +
	"MapMessage\x120\n" +
	"\astr_str\x18\x01 \x03(\v2\x17.MapMessage.StrStrEntryR\x06strStr\x120\n" +
	"\aint_str\x18\x02 \x03(\v2\x17.MapMessage.IntStrEntryR\x06intStr\x120\n" +
	"\astr_msg\x18\x03 \x03(\v2\x17.MapMessage.StrMsgEntryR\x06strMsg\x1a9\n" +
	"\vStrStrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vIntStrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\vStrMsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".MapSubMsgR\x05value:\x028\x01b\x06proto3"

var (
	file_map3_proto_rawDescOnce sync.Once
	file_map3_proto_rawDescData []byte
)

func file_map3_proto_rawDescGZIP() []byte {
	file_map3_proto_rawDescOnce.Do(func() {
		file_map3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_map3_proto_rawDesc), len(file_map3_proto_rawDesc)))
	})
	return file_map3_proto_rawDescData
}

var file_map3_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_map3_proto_goTypes = []any{
	(*MapSubMsg)(nil),  // 0: MapSubMsg
	(*MapMessage)(nil), // 1: MapMessage
	nil,                // 2: MapMessage.StrStrEntry
	nil,                // 3: MapMessage.IntStrEntry
	nil,                // 4: MapMessage.StrMsgEntry
}
var file_map3_proto_depIdxs = []int32{
	2, // 0: MapMessage.str_str:type_name -> MapMessage.StrStrEntry
	3, // 1: MapMessage.int_str:type_name -> MapMessage.IntStrEntry
	4, // 2: MapMessage.str_msg:type_name -> MapMessage.StrMsgEntry
	0, // 3: MapMessage.StrMsgEntry.value:type_name -> MapSubMsg
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_map3_proto_init() }
func file_map3_proto_init() {
	if File_map3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_map3_proto_rawDesc), len(file_map3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_map3_proto_goTypes,
		DependencyIndexes: file_map3_proto_depIdxs,
		MessageInfos:      file_map3_proto_msgTypes,
	}.Build()
	File_map3_proto = out.File
	file_map3_proto_goTypes = nil
	file_map3_proto_depIdxs = nil
}
