// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nested3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_nested3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_nested3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_nested3_proto_rawDescGZIP(), []int{0}
}

func (x *Inner) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Inner) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Middle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *Inner                 `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Middle) Reset() {
	*x = Middle{}
	mi := &file_nested3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middle) ProtoMessage() {}

func (x *Middle) ProtoReflect() protoreflect.Message {
	mi := &file_nested3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middle.ProtoReflect.Descriptor instead.
func (*Middle) Descriptor() ([]byte, []int) {
	return file_nested3_proto_rawDescGZIP(), []int{1}
}

func (x *Middle) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Middle) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Outer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middle        *Middle                `protobuf:"bytes,1,opt,name=middle,proto3" json:"middle,omitempty"`
	DirectInner   *Inner                 `protobuf:"bytes,2,opt,name=direct_inner,json=directInner,proto3" json:"direct_inner,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_nested3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_nested3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_nested3_proto_rawDescGZIP(), []int{2}
}

func (x *Outer) GetMiddle() *Middle {
	if x != nil {
		return x.Middle
	}
	return nil
}

func (x *Outer) GetDirectInner() *Inner {
	if x != nil {
		return x.DirectInner
	}
	return nil
}

func (x *Outer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_nested3_proto protoreflect.FileDescriptor

const file_nested3_proto_rawDesc = "" +
	"\n" +
	"\rnested3.proto\"3\n" +
	"\x05Inner\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"6\n" +
	"\x06Middle\x12\x1c\n" +
	"\x05inner\x18\x01 \x01(\v2\x06.InnerR\x05inner\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"g\n" +
	"\x05Outer\x12\x1f\n" +
	"\x06middle\x18\x01 \x01(\v2\a.MiddleR\x06middle\x12)\n" +
	"\fdirect_inner\x18\x02 \x01(\v2\x06.InnerR\vdirectInner\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameb\x06proto3"

var (
	file_nested3_proto_rawDescOnce sync.Once
	file_nested3_proto_rawDescData []byte
)

func file_nested3_proto_rawDescGZIP() []byte {
	file_nested3_proto_rawDescOnce.Do(func() {
		file_nested3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nested3_proto_rawDesc), len(file_nested3_proto_rawDesc)))
	})
	return file_nested3_proto_rawDescData
}

var file_nested3_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nested3_proto_goTypes = []any{
	(*Inner)(nil),  // 0: Inner
	(*Middle)(nil), // 1: Middle
	(*Outer)(nil),  // 2: Outer
}
var file_nested3_proto_depIdxs = []int32{
	0, // 0: Middle.inner:type_name -> Inner
	1, // 1: Outer.middle:type_name -> Middle
	0, // 2: Outer.direct_inner:type_name -> Inner
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nested3_proto_init() }
func file_nested3_proto_init() {
	if File_nested3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nested3_proto_rawDesc), len(file_nested3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nested3_proto_goTypes,
		DependencyIndexes: file_nested3_proto_depIdxs,
		MessageInfos:      file_nested3_proto_msgTypes,
	}.Build()
	File_nested3_proto = out.File
	file_nested3_proto_goTypes = nil
	file_nested3_proto_depIdxs = nil
}
