// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: oneof3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubMsg) Reset() {
	*x = SubMsg{}
	mi := &file_oneof3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMsg) ProtoMessage() {}

func (x *SubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_oneof3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMsg.ProtoReflect.Descriptor instead.
func (*SubMsg) Descriptor() ([]byte, []int) {
	return file_oneof3_proto_rawDescGZIP(), []int{0}
}

func (x *SubMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type OneofMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*OneofMessage_StrVal
	//	*OneofMessage_IntVal
	//	*OneofMessage_BytesVal
	//	*OneofMessage_MsgVal
	Value         isOneofMessage_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofMessage) Reset() {
	*x = OneofMessage{}
	mi := &file_oneof3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofMessage) ProtoMessage() {}

func (x *OneofMessage) ProtoReflect() protoreflect.Message {
	mi := &file_oneof3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofMessage.ProtoReflect.Descriptor instead.
func (*OneofMessage) Descriptor() ([]byte, []int) {
	return file_oneof3_proto_rawDescGZIP(), []int{1}
}

func (x *OneofMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OneofMessage) GetValue() isOneofMessage_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OneofMessage) GetStrVal() string {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *OneofMessage) GetIntVal() int32 {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *OneofMessage) GetBytesVal() []byte {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_BytesVal); ok {
			return x.BytesVal
		}
	}
	return nil
}

func (x *OneofMessage) GetMsgVal() *SubMsg {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_MsgVal); ok {
			return x.MsgVal
		}
	}
	return nil
}

type isOneofMessage_Value interface {
	isOneofMessage_Value()
}

type OneofMessage_StrVal struct {
	StrVal string `protobuf:"bytes,10,opt,name=str_val,json=strVal,proto3,oneof"`
}

type OneofMessage_IntVal struct {
	IntVal int32 `protobuf:"varint,11,opt,name=int_val,json=intVal,proto3,oneof"`
}

type OneofMessage_BytesVal struct {
	BytesVal []byte `protobuf:"bytes,12,opt,name=bytes_val,json=bytesVal,proto3,oneof"`
}

type OneofMessage_MsgVal struct {
	MsgVal *SubMsg `protobuf:"bytes,13,opt,name=msg_val,json=msgVal,proto3,oneof"`
}

func (*OneofMessage_StrVal) isOneofMessage_Value() {}

func (*OneofMessage_IntVal) isOneofMessage_Value() {}

func (*OneofMessage_BytesVal) isOneofMessage_Value() {}

func (*OneofMessage_MsgVal) isOneofMessage_Value() {}

var File_oneof3_proto protoreflect.FileDescriptor

const file_oneof3_proto_rawDesc = "" +
	"\n" +
	"\foneof3.proto\",\n" +
	"\x06SubMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xa4\x01\n" +
	"\fOneofMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\astr_val\x18\n" +
	" \x01(\tH\x00R\x06strVal\x12\x19\n" +
	"\aint_val\x18\v \x01(\x05H\x00R\x06intVal\x12\x1d\n" +
	"\tbytes_val\x18\f \x01(\fH\x00R\bbytesVal\x12\"\n" +
	"\amsg_val\x18\r \x01(\v2\a.SubMsgH\x00R\x06msgValB\a\n" +
	"\x05valueb\x06proto3"

var (
	file_oneof3_proto_rawDescOnce sync.Once
	file_oneof3_proto_rawDescData []byte
)

func file_oneof3_proto_rawDescGZIP() []byte {
	file_oneof3_proto_rawDescOnce.Do(func() {
		file_oneof3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oneof3_proto_rawDesc), len(file_oneof3_proto_rawDesc)))
	})
	return file_oneof3_proto_rawDescData
}

var file_oneof3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oneof3_proto_goTypes = []any{
	(*SubMsg)(nil),       // 0: SubMsg
	(*OneofMessage)(nil), // 1: OneofMessage
}
var file_oneof3_proto_depIdxs = []int32{
	0, // 0: OneofMessage.msg_val:type_name -> SubMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oneof3_proto_init() }
func file_oneof3_proto_init() {
	if File_oneof3_proto != nil {
		return
	}
	file_oneof3_proto_msgTypes[1].OneofWrappers = []any{
		(*OneofMessage_StrVal)(nil),
		(*OneofMessage_IntVal)(nil),
		(*OneofMessage_BytesVal)(nil),
		(*OneofMessage_MsgVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oneof3_proto_rawDesc), len(file_oneof3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneof3_proto_goTypes,
		DependencyIndexes: file_oneof3_proto_depIdxs,
		MessageInfos:      file_oneof3_proto_msgTypes,
	}.Build()
	File_oneof3_proto = out.File
	file_oneof3_proto_goTypes = nil
	file_oneof3_proto_depIdxs = nil
}
