// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: optional3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptInt        *int32                 `protobuf:"varint,1,opt,name=opt_int,json=optInt,proto3,oneof" json:"opt_int,omitempty"`
	OptStr        *string                `protobuf:"bytes,2,opt,name=opt_str,json=optStr,proto3,oneof" json:"opt_str,omitempty"`
	OptBool       *bool                  `protobuf:"varint,3,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	OptDouble     *float64               `protobuf:"fixed64,4,opt,name=opt_double,json=optDouble,proto3,oneof" json:"opt_double,omitempty"`
	RegularInt    int32                  `protobuf:"varint,5,opt,name=regular_int,json=regularInt,proto3" json:"regular_int,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalMessage) Reset() {
	*x = OptionalMessage{}
	mi := &file_optional3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalMessage) ProtoMessage() {}

func (x *OptionalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_optional3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalMessage.ProtoReflect.Descriptor instead.
func (*OptionalMessage) Descriptor() ([]byte, []int) {
	return file_optional3_proto_rawDescGZIP(), []int{0}
}

func (x *OptionalMessage) GetOptInt() int32 {
	if x != nil && x.OptInt != nil {
		return *x.OptInt
	}
	return 0
}

func (x *OptionalMessage) GetOptStr() string {
	if x != nil && x.OptStr != nil {
		return *x.OptStr
	}
	return ""
}

func (x *OptionalMessage) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *OptionalMessage) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return 0
}

func (x *OptionalMessage) GetRegularInt() int32 {
	if x != nil {
		return x.RegularInt
	}
	return 0
}

var File_optional3_proto protoreflect.FileDescriptor

const file_optional3_proto_rawDesc = "" +
	"\n" +
	"\x0foptional3.proto\"\xe6\x01\n" +
	"\x0fOptionalMessage\x12\x1c\n" +
	"\aopt_int\x18\x01 \x01(\x05H\x00R\x06optInt\x88\x01\x01\x12\x1c\n" +
	"\aopt_str\x18\x02 \x01(\tH\x01R\x06optStr\x88\x01\x01\x12\x1e\n" +
	"\bopt_bool\x18\x03 \x01(\bH\x02R\aoptBool\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_double\x18\x04 \x01(\x01H\x03R\toptDouble\x88\x01\x01\x12\x1f\n" +
	"\vregular_int\x18\x05 \x01(\x05R\n" +
	"regularIntB\n" +
	"\n" +
	"\b_opt_intB\n" +
	"\n" +
	"\b_opt_strB\v\n" +
	"\t_opt_boolB\r\n" +
	"\v_opt_doubleb\x06proto3"

var (
	file_optional3_proto_rawDescOnce sync.Once
	file_optional3_proto_rawDescData []byte
)

func file_optional3_proto_rawDescGZIP() []byte {
	file_optional3_proto_rawDescOnce.Do(func() {
		file_optional3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optional3_proto_rawDesc), len(file_optional3_proto_rawDesc)))
	})
	return file_optional3_proto_rawDescData
}

var file_optional3_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_optional3_proto_goTypes = []any{
	(*OptionalMessage)(nil), // 0: OptionalMessage
}
var file_optional3_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_optional3_proto_init() }
func file_optional3_proto_init() {
	if File_optional3_proto != nil {
		return
	}
	file_optional3_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optional3_proto_rawDesc), len(file_optional3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optional3_proto_goTypes,
		DependencyIndexes: file_optional3_proto_depIdxs,
		MessageInfos:      file_optional3_proto_msgTypes,
	}.Build()
	File_optional3_proto = out.File
	file_optional3_proto_goTypes = nil
	file_optional3_proto_depIdxs = nil
}
