// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: required2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Required2Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,req,name=req_id,json=reqId" json:"req_id,omitempty"`
	ReqName       *string                `protobuf:"bytes,2,req,name=req_name,json=reqName" json:"req_name,omitempty"`
	OptValue      *int32                 `protobuf:"varint,3,opt,name=opt_value,json=optValue" json:"opt_value,omitempty"`
	OptLabel      *string                `protobuf:"bytes,4,opt,name=opt_label,json=optLabel" json:"opt_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Required2Message) Reset() {
	*x = Required2Message{}
	mi := &file_required2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Required2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Required2Message) ProtoMessage() {}

func (x *Required2Message) ProtoReflect() protoreflect.Message {
	mi := &file_required2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Required2Message.ProtoReflect.Descriptor instead.
func (*Required2Message) Descriptor() ([]byte, []int) {
	return file_required2_proto_rawDescGZIP(), []int{0}
}

func (x *Required2Message) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *Required2Message) GetReqName() string {
	if x != nil && x.ReqName != nil {
		return *x.ReqName
	}
	return ""
}

func (x *Required2Message) GetOptValue() int32 {
	if x != nil && x.OptValue != nil {
		return *x.OptValue
	}
	return 0
}

func (x *Required2Message) GetOptLabel() string {
	if x != nil && x.OptLabel != nil {
		return *x.OptLabel
	}
	return ""
}

var File_required2_proto protoreflect.FileDescriptor

const file_required2_proto_rawDesc = "" +
	"\n" +
	"\x0frequired2.proto\"~\n" +
	"\x10Required2Message\x12\x15\n" +
	"\x06req_id\x18\x01 \x02(\x05R\x05reqId\x12\x19\n" +
	"\breq_name\x18\x02 \x02(\tR\areqName\x12\x1b\n" +
	"\topt_value\x18\x03 \x01(\x05R\boptValue\x12\x1b\n" +
	"\topt_label\x18\x04 \x01(\tR\boptLabel"

var (
	file_required2_proto_rawDescOnce sync.Once
	file_required2_proto_rawDescData []byte
)

func file_required2_proto_rawDescGZIP() []byte {
	file_required2_proto_rawDescOnce.Do(func() {
		file_required2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_required2_proto_rawDesc), len(file_required2_proto_rawDesc)))
	})
	return file_required2_proto_rawDescData
}

var file_required2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_required2_proto_goTypes = []any{
	(*Required2Message)(nil), // 0: Required2Message
}
var file_required2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_required2_proto_init() }
func file_required2_proto_init() {
	if File_required2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_required2_proto_rawDesc), len(file_required2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_required2_proto_goTypes,
		DependencyIndexes: file_required2_proto_depIdxs,
		MessageInfos:      file_required2_proto_msgTypes,
	}.Build()
	File_required2_proto = out.File
	file_required2_proto_goTypes = nil
	file_required2_proto_depIdxs = nil
}
