// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: scalar3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalarMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FDouble       float64                `protobuf:"fixed64,1,opt,name=f_double,json=fDouble,proto3" json:"f_double,omitempty"`
	FFloat        float32                `protobuf:"fixed32,2,opt,name=f_float,json=fFloat,proto3" json:"f_float,omitempty"`
	FInt32        int32                  `protobuf:"varint,3,opt,name=f_int32,json=fInt32,proto3" json:"f_int32,omitempty"`
	FInt64        int64                  `protobuf:"varint,4,opt,name=f_int64,json=fInt64,proto3" json:"f_int64,omitempty"`
	FUint32       uint32                 `protobuf:"varint,5,opt,name=f_uint32,json=fUint32,proto3" json:"f_uint32,omitempty"`
	FUint64       uint64                 `protobuf:"varint,6,opt,name=f_uint64,json=fUint64,proto3" json:"f_uint64,omitempty"`
	FSint32       int32                  `protobuf:"zigzag32,7,opt,name=f_sint32,json=fSint32,proto3" json:"f_sint32,omitempty"`
	FSint64       int64                  `protobuf:"zigzag64,8,opt,name=f_sint64,json=fSint64,proto3" json:"f_sint64,omitempty"`
	FFixed32      uint32                 `protobuf:"fixed32,9,opt,name=f_fixed32,json=fFixed32,proto3" json:"f_fixed32,omitempty"`
	FFixed64      uint64                 `protobuf:"fixed64,10,opt,name=f_fixed64,json=fFixed64,proto3" json:"f_fixed64,omitempty"`
	FSfixed32     int32                  `protobuf:"fixed32,11,opt,name=f_sfixed32,json=fSfixed32,proto3" json:"f_sfixed32,omitempty"`
	FSfixed64     int64                  `protobuf:"fixed64,12,opt,name=f_sfixed64,json=fSfixed64,proto3" json:"f_sfixed64,omitempty"`
	FBool         bool                   `protobuf:"varint,13,opt,name=f_bool,json=fBool,proto3" json:"f_bool,omitempty"`
	FString       string                 `protobuf:"bytes,14,opt,name=f_string,json=fString,proto3" json:"f_string,omitempty"`
	FBytes        []byte                 `protobuf:"bytes,15,opt,name=f_bytes,json=fBytes,proto3" json:"f_bytes,omitempty"`
	FLargeTag     int32                  `protobuf:"varint,1000,opt,name=f_large_tag,json=fLargeTag,proto3" json:"f_large_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarMessage) Reset() {
	*x = ScalarMessage{}
	mi := &file_scalar3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarMessage) ProtoMessage() {}

func (x *ScalarMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scalar3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarMessage.ProtoReflect.Descriptor instead.
func (*ScalarMessage) Descriptor() ([]byte, []int) {
	return file_scalar3_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarMessage) GetFDouble() float64 {
	if x != nil {
		return x.FDouble
	}
	return 0
}

func (x *ScalarMessage) GetFFloat() float32 {
	if x != nil {
		return x.FFloat
	}
	return 0
}

func (x *ScalarMessage) GetFInt32() int32 {
	if x != nil {
		return x.FInt32
	}
	return 0
}

func (x *ScalarMessage) GetFInt64() int64 {
	if x != nil {
		return x.FInt64
	}
	return 0
}

func (x *ScalarMessage) GetFUint32() uint32 {
	if x != nil {
		return x.FUint32
	}
	return 0
}

func (x *ScalarMessage) GetFUint64() uint64 {
	if x != nil {
		return x.FUint64
	}
	return 0
}

func (x *ScalarMessage) GetFSint32() int32 {
	if x != nil {
		return x.FSint32
	}
	return 0
}

func (x *ScalarMessage) GetFSint64() int64 {
	if x != nil {
		return x.FSint64
	}
	return 0
}

func (x *ScalarMessage) GetFFixed32() uint32 {
	if x != nil {
		return x.FFixed32
	}
	return 0
}

func (x *ScalarMessage) GetFFixed64() uint64 {
	if x != nil {
		return x.FFixed64
	}
	return 0
}

func (x *ScalarMessage) GetFSfixed32() int32 {
	if x != nil {
		return x.FSfixed32
	}
	return 0
}

func (x *ScalarMessage) GetFSfixed64() int64 {
	if x != nil {
		return x.FSfixed64
	}
	return 0
}

func (x *ScalarMessage) GetFBool() bool {
	if x != nil {
		return x.FBool
	}
	return false
}

func (x *ScalarMessage) GetFString() string {
	if x != nil {
		return x.FString
	}
	return ""
}

func (x *ScalarMessage) GetFBytes() []byte {
	if x != nil {
		return x.FBytes
	}
	return nil
}

func (x *ScalarMessage) GetFLargeTag() int32 {
	if x != nil {
		return x.FLargeTag
	}
	return 0
}

var File_scalar3_proto protoreflect.FileDescriptor

const file_scalar3_proto_rawDesc = "" +
	"\n" +
	"\rscalar3.proto\"\xc5\x03\n" +
	"\rScalarMessage\x12\x19\n" +
	"\bf_double\x18\x01 \x01(\x01R\afDouble\x12\x17\n" +
	"\af_float\x18\x02 \x01(\x02R\x06fFloat\x12\x17\n" +
	"\af_int32\x18\x03 \x01(\x05R\x06fInt32\x12\x17\n" +
	"\af_int64\x18\x04 \x01(\x03R\x06fInt64\x12\x19\n" +
	"\bf_uint32\x18\x05 \x01(\rR\afUint32\x12\x19\n" +
	"\bf_uint64\x18\x06 \x01(\x04R\afUint64\x12\x19\n" +
	"\bf_sint32\x18\a \x01(\x11R\afSint32\x12\x19\n" +
	"\bf_sint64\x18\b \x01(\x12R\afSint64\x12\x1b\n" +
	"\tf_fixed32\x18\t \x01(\aR\bfFixed32\x12\x1b\n" +
	"\tf_fixed64\x18\n" +
	" \x01(\x06R\bfFixed64\x12\x1d\n" +
	"\n" +
	"f_sfixed32\x18\v \x01(\x0fR\tfSfixed32\x12\x1d\n" +
	"\n" +
	"f_sfixed64\x18\f \x01(\x10R\tfSfixed64\x12\x15\n" +
	"\x06f_bool\x18\r \x01(\bR\x05fBool\x12\x19\n" +
	"\bf_string\x18\x0e \x01(\tR\afString\x12\x17\n" +
	"\af_bytes\x18\x0f \x01(\fR\x06fBytes\x12\x1f\n" +
	"\vf_large_tag\x18\xe8\a \x01(\x05R\tfLargeTagb\x06proto3"

var (
	file_scalar3_proto_rawDescOnce sync.Once
	file_scalar3_proto_rawDescData []byte
)

func file_scalar3_proto_rawDescGZIP() []byte {
	file_scalar3_proto_rawDescOnce.Do(func() {
		file_scalar3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalar3_proto_rawDesc), len(file_scalar3_proto_rawDesc)))
	})
	return file_scalar3_proto_rawDescData
}

var file_scalar3_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scalar3_proto_goTypes = []any{
	(*ScalarMessage)(nil), // 0: ScalarMessage
}
var file_scalar3_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scalar3_proto_init() }
func file_scalar3_proto_init() {
	if File_scalar3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalar3_proto_rawDesc), len(file_scalar3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scalar3_proto_goTypes,
		DependencyIndexes: file_scalar3_proto_depIdxs,
		MessageInfos:      file_scalar3_proto_msgTypes,
	}.Build()
	File_scalar3_proto = out.File
	file_scalar3_proto_goTypes = nil
	file_scalar3_proto_depIdxs = nil
}
