// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_streaming.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_service_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_service_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_service_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_service_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StreamResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_service_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_service_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_service_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int32                  `protobuf:"varint,1,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_service_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_service_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResult) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *UploadResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_service_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_service_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_service_streaming_proto protoreflect.FileDescriptor

const file_service_streaming_proto_rawDesc = "" +
	"\n" +
	"\x17service_streaming.proto\"%\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\">\n" +
	"\x0eStreamResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\"!\n" +
	"\vUploadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"K\n" +
	"\fUploadResult\x12!\n" +
	"\ftotal_chunks\x18\x01 \x01(\x05R\vtotalChunks\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"9\n" +
	"\vChatMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text2\xcf\x01\n" +
	"\x10StreamingService\x12,\n" +
	"\tUnaryCall\x12\x0e.StreamRequest\x1a\x0f.StreamResponse\x12/\n" +
	"\n" +
	"ServerSide\x12\x0e.StreamRequest\x1a\x0f.StreamResponse0\x01\x12+\n" +
	"\n" +
	"ClientSide\x12\f.UploadChunk\x1a\r.UploadResult(\x01\x12/\n" +
	"\rBidirectional\x12\f.ChatMessage\x1a\f.ChatMessage(\x010\x01b\x06proto3"

var (
	file_service_streaming_proto_rawDescOnce sync.Once
	file_service_streaming_proto_rawDescData []byte
)

func file_service_streaming_proto_rawDescGZIP() []byte {
	file_service_streaming_proto_rawDescOnce.Do(func() {
		file_service_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_streaming_proto_rawDesc), len(file_service_streaming_proto_rawDesc)))
	})
	return file_service_streaming_proto_rawDescData
}

var file_service_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_service_streaming_proto_goTypes = []any{
	(*StreamRequest)(nil),  // 0: StreamRequest
	(*StreamResponse)(nil), // 1: StreamResponse
	(*UploadChunk)(nil),    // 2: UploadChunk
	(*UploadResult)(nil),   // 3: UploadResult
	(*ChatMessage)(nil),    // 4: ChatMessage
}
var file_service_streaming_proto_depIdxs = []int32{
	0, // 0: StreamingService.UnaryCall:input_type -> StreamRequest
	0, // 1: StreamingService.ServerSide:input_type -> StreamRequest
	2, // 2: StreamingService.ClientSide:input_type -> UploadChunk
	4, // 3: StreamingService.Bidirectional:input_type -> ChatMessage
	1, // 4: StreamingService.UnaryCall:output_type -> StreamResponse
	1, // 5: StreamingService.ServerSide:output_type -> StreamResponse
	3, // 6: StreamingService.ClientSide:output_type -> UploadResult
	4, // 7: StreamingService.Bidirectional:output_type -> ChatMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_streaming_proto_init() }
func file_service_streaming_proto_init() {
	if File_service_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_streaming_proto_rawDesc), len(file_service_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_streaming_proto_goTypes,
		DependencyIndexes: file_service_streaming_proto_depIdxs,
		MessageInfos:      file_service_streaming_proto_msgTypes,
	}.Build()
	File_service_streaming_proto = out.File
	file_service_streaming_proto_goTypes = nil
	file_service_streaming_proto_depIdxs = nil
}
