// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_LOW      Priority = 0
	Priority_MEDIUM   Priority = 1
	Priority_HIGH     Priority = 2
	Priority_CRITICAL Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
		3: "CRITICAL",
	}
	Priority_value = map[string]int32{
		"LOW":      0,
		"MEDIUM":   1,
		"HIGH":     2,
		"CRITICAL": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_service_types_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_service_types_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_service_types_proto_rawDescGZIP(), []int{0}
}

type InnerDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerDetail) Reset() {
	*x = InnerDetail{}
	mi := &file_service_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerDetail) ProtoMessage() {}

func (x *InnerDetail) ProtoReflect() protoreflect.Message {
	mi := &file_service_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerDetail.ProtoReflect.Descriptor instead.
func (*InnerDetail) Descriptor() ([]byte, []int) {
	return file_service_types_proto_rawDescGZIP(), []int{0}
}

func (x *InnerDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ComplexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=Priority" json:"priority,omitempty"`
	Detail        *InnerDetail           `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexRequest) Reset() {
	*x = ComplexRequest{}
	mi := &file_service_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexRequest) ProtoMessage() {}

func (x *ComplexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexRequest.ProtoReflect.Descriptor instead.
func (*ComplexRequest) Descriptor() ([]byte, []int) {
	return file_service_types_proto_rawDescGZIP(), []int{1}
}

func (x *ComplexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComplexRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_LOW
}

func (x *ComplexRequest) GetDetail() *InnerDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *ComplexRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ComplexRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ComplexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=Priority" json:"priority,omitempty"`
	Details       []*InnerDetail         `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexResponse) Reset() {
	*x = ComplexResponse{}
	mi := &file_service_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexResponse) ProtoMessage() {}

func (x *ComplexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexResponse.ProtoReflect.Descriptor instead.
func (*ComplexResponse) Descriptor() ([]byte, []int) {
	return file_service_types_proto_rawDescGZIP(), []int{2}
}

func (x *ComplexResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ComplexResponse) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_LOW
}

func (x *ComplexResponse) GetDetails() []*InnerDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_service_types_proto protoreflect.FileDescriptor

const file_service_types_proto_rawDesc = "" +
	"\n" +
	"\x13service_types.proto\"/\n" +
	"\vInnerDetail\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"\xfd\x01\n" +
	"\x0eComplexRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\bpriority\x18\x02 \x01(\x0e2\t.PriorityR\bpriority\x12$\n" +
	"\x06detail\x18\x03 \x01(\v2\f.InnerDetailR\x06detail\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x129\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1d.ComplexRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x0fComplexResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\bpriority\x18\x02 \x01(\x0e2\t.PriorityR\bpriority\x12&\n" +
	"\adetails\x18\x03 \x03(\v2\f.InnerDetailR\adetails*7\n" +
	"\bPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x032y\n" +
	"\fTypesService\x123\n" +
	"\x0eProcessComplex\x12\x0f.ComplexRequest\x1a\x10.ComplexResponse\x124\n" +
	"\rStreamComplex\x12\x0f.ComplexRequest\x1a\x10.ComplexResponse0\x01b\x06proto3"

var (
	file_service_types_proto_rawDescOnce sync.Once
	file_service_types_proto_rawDescData []byte
)

func file_service_types_proto_rawDescGZIP() []byte {
	file_service_types_proto_rawDescOnce.Do(func() {
		file_service_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_types_proto_rawDesc), len(file_service_types_proto_rawDesc)))
	})
	return file_service_types_proto_rawDescData
}

var file_service_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_types_proto_goTypes = []any{
	(Priority)(0),           // 0: Priority
	(*InnerDetail)(nil),     // 1: InnerDetail
	(*ComplexRequest)(nil),  // 2: ComplexRequest
	(*ComplexResponse)(nil), // 3: ComplexResponse
	nil,                     // 4: ComplexRequest.MetadataEntry
}
var file_service_types_proto_depIdxs = []int32{
	0, // 0: ComplexRequest.priority:type_name -> Priority
	1, // 1: ComplexRequest.detail:type_name -> InnerDetail
	4, // 2: ComplexRequest.metadata:type_name -> ComplexRequest.MetadataEntry
	0, // 3: ComplexResponse.priority:type_name -> Priority
	1, // 4: ComplexResponse.details:type_name -> InnerDetail
	2, // 5: TypesService.ProcessComplex:input_type -> ComplexRequest
	2, // 6: TypesService.StreamComplex:input_type -> ComplexRequest
	3, // 7: TypesService.ProcessComplex:output_type -> ComplexResponse
	3, // 8: TypesService.StreamComplex:output_type -> ComplexResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_service_types_proto_init() }
func file_service_types_proto_init() {
	if File_service_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_types_proto_rawDesc), len(file_service_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_types_proto_goTypes,
		DependencyIndexes: file_service_types_proto_depIdxs,
		EnumInfos:         file_service_types_proto_enumTypes,
		MessageInfos:      file_service_types_proto_msgTypes,
	}.Build()
	File_service_types_proto = out.File
	file_service_types_proto_goTypes = nil
	file_service_types_proto_depIdxs = nil
}
