// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_edge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeRequest) Reset() {
	*x = EdgeRequest{}
	mi := &file_service_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeRequest) ProtoMessage() {}

func (x *EdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeRequest.ProtoReflect.Descriptor instead.
func (*EdgeRequest) Descriptor() ([]byte, []int) {
	return file_service_edge_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EdgeRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type EdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeResponse) Reset() {
	*x = EdgeResponse{}
	mi := &file_service_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeResponse) ProtoMessage() {}

func (x *EdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeResponse.ProtoReflect.Descriptor instead.
func (*EdgeResponse) Descriptor() ([]byte, []int) {
	return file_service_edge_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EdgeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_service_edge_proto protoreflect.FileDescriptor

const file_service_edge_proto_rawDesc = "" +
	"\n" +
	"\x12service_edge.proto\"3\n" +
	"\vEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"6\n" +
	"\fEdgeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2@\n" +
	"\x13SingleMethodService\x12)\n" +
	"\n" +
	"OnlyMethod\x12\f.EdgeRequest\x1a\r.EdgeResponse2\xc9\x02\n" +
	"\x12ManyMethodsService\x12%\n" +
	"\x06Create\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12#\n" +
	"\x04Read\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12%\n" +
	"\x06Update\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12%\n" +
	"\x06Delete\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12#\n" +
	"\x04List\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12$\n" +
	"\x05Count\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12%\n" +
	"\x06Exists\x12\f.EdgeRequest\x1a\r.EdgeResponse\x12'\n" +
	"\bValidate\x12\f.EdgeRequest\x1a\r.EdgeResponseb\x06proto3"

var (
	file_service_edge_proto_rawDescOnce sync.Once
	file_service_edge_proto_rawDescData []byte
)

func file_service_edge_proto_rawDescGZIP() []byte {
	file_service_edge_proto_rawDescOnce.Do(func() {
		file_service_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_edge_proto_rawDesc), len(file_service_edge_proto_rawDesc)))
	})
	return file_service_edge_proto_rawDescData
}

var file_service_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_edge_proto_goTypes = []any{
	(*EdgeRequest)(nil),  // 0: EdgeRequest
	(*EdgeResponse)(nil), // 1: EdgeResponse
}
var file_service_edge_proto_depIdxs = []int32{
	0, // 0: SingleMethodService.OnlyMethod:input_type -> EdgeRequest
	0, // 1: ManyMethodsService.Create:input_type -> EdgeRequest
	0, // 2: ManyMethodsService.Read:input_type -> EdgeRequest
	0, // 3: ManyMethodsService.Update:input_type -> EdgeRequest
	0, // 4: ManyMethodsService.Delete:input_type -> EdgeRequest
	0, // 5: ManyMethodsService.List:input_type -> EdgeRequest
	0, // 6: ManyMethodsService.Count:input_type -> EdgeRequest
	0, // 7: ManyMethodsService.Exists:input_type -> EdgeRequest
	0, // 8: ManyMethodsService.Validate:input_type -> EdgeRequest
	1, // 9: SingleMethodService.OnlyMethod:output_type -> EdgeResponse
	1, // 10: ManyMethodsService.Create:output_type -> EdgeResponse
	1, // 11: ManyMethodsService.Read:output_type -> EdgeResponse
	1, // 12: ManyMethodsService.Update:output_type -> EdgeResponse
	1, // 13: ManyMethodsService.Delete:output_type -> EdgeResponse
	1, // 14: ManyMethodsService.List:output_type -> EdgeResponse
	1, // 15: ManyMethodsService.Count:output_type -> EdgeResponse
	1, // 16: ManyMethodsService.Exists:output_type -> EdgeResponse
	1, // 17: ManyMethodsService.Validate:output_type -> EdgeResponse
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_edge_proto_init() }
func file_service_edge_proto_init() {
	if File_service_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_edge_proto_rawDesc), len(file_service_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_edge_proto_goTypes,
		DependencyIndexes: file_service_edge_proto_depIdxs,
		MessageInfos:      file_service_edge_proto_msgTypes,
	}.Build()
	File_service_edge_proto = out.File
	file_service_edge_proto_goTypes = nil
	file_service_edge_proto_depIdxs = nil
}
