// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_package.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_service_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_service_package_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_service_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_service_package_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_service_package_proto protoreflect.FileDescriptor

const file_service_package_proto_rawDesc = "" +
	"\n" +
	"\x15service_package.proto\x12\x11myapp.services.v1\"!\n" +
	"\rLookupRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"<\n" +
	"\x0eLookupResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\xb6\x01\n" +
	"\x0fPackagedService\x12M\n" +
	"\x06Lookup\x12 .myapp.services.v1.LookupRequest\x1a!.myapp.services.v1.LookupResponse\x12T\n" +
	"\rReverseLookup\x12!.myapp.services.v1.LookupResponse\x1a .myapp.services.v1.LookupRequestb\x06proto3"

var (
	file_service_package_proto_rawDescOnce sync.Once
	file_service_package_proto_rawDescData []byte
)

func file_service_package_proto_rawDescGZIP() []byte {
	file_service_package_proto_rawDescOnce.Do(func() {
		file_service_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_package_proto_rawDesc), len(file_service_package_proto_rawDesc)))
	})
	return file_service_package_proto_rawDescData
}

var file_service_package_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_package_proto_goTypes = []any{
	(*LookupRequest)(nil),  // 0: myapp.services.v1.LookupRequest
	(*LookupResponse)(nil), // 1: myapp.services.v1.LookupResponse
}
var file_service_package_proto_depIdxs = []int32{
	0, // 0: myapp.services.v1.PackagedService.Lookup:input_type -> myapp.services.v1.LookupRequest
	1, // 1: myapp.services.v1.PackagedService.ReverseLookup:input_type -> myapp.services.v1.LookupResponse
	1, // 2: myapp.services.v1.PackagedService.Lookup:output_type -> myapp.services.v1.LookupResponse
	0, // 3: myapp.services.v1.PackagedService.ReverseLookup:output_type -> myapp.services.v1.LookupRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_package_proto_init() }
func file_service_package_proto_init() {
	if File_service_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_package_proto_rawDesc), len(file_service_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_package_proto_goTypes,
		DependencyIndexes: file_service_package_proto_depIdxs,
		MessageInfos:      file_service_package_proto_msgTypes,
	}.Build()
	File_service_package_proto = out.File
	file_service_package_proto_goTypes = nil
	file_service_package_proto_depIdxs = nil
}
