// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_multi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestA) Reset() {
	*x = RequestA{}
	mi := &file_service_multi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestA) ProtoMessage() {}

func (x *RequestA) ProtoReflect() protoreflect.Message {
	mi := &file_service_multi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestA.ProtoReflect.Descriptor instead.
func (*RequestA) Descriptor() ([]byte, []int) {
	return file_service_multi_proto_rawDescGZIP(), []int{0}
}

func (x *RequestA) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseA) Reset() {
	*x = ResponseA{}
	mi := &file_service_multi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseA) ProtoMessage() {}

func (x *ResponseA) ProtoReflect() protoreflect.Message {
	mi := &file_service_multi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseA.ProtoReflect.Descriptor instead.
func (*ResponseA) Descriptor() ([]byte, []int) {
	return file_service_multi_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseA) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type RequestB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestB) Reset() {
	*x = RequestB{}
	mi := &file_service_multi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestB) ProtoMessage() {}

func (x *RequestB) ProtoReflect() protoreflect.Message {
	mi := &file_service_multi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestB.ProtoReflect.Descriptor instead.
func (*RequestB) Descriptor() ([]byte, []int) {
	return file_service_multi_proto_rawDescGZIP(), []int{2}
}

func (x *RequestB) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RequestB) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ResponseB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseB) Reset() {
	*x = ResponseB{}
	mi := &file_service_multi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseB) ProtoMessage() {}

func (x *ResponseB) ProtoReflect() protoreflect.Message {
	mi := &file_service_multi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseB.ProtoReflect.Descriptor instead.
func (*ResponseB) Descriptor() ([]byte, []int) {
	return file_service_multi_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseB) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ResponseB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_service_multi_proto protoreflect.FileDescriptor

const file_service_multi_proto_rawDesc = "" +
	"\n" +
	"\x13service_multi.proto\"\x1e\n" +
	"\bRequestA\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\tResponseA\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"6\n" +
	"\bRequestB\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"E\n" +
	"\tResponseB\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2V\n" +
	"\fFirstService\x12\"\n" +
	"\tMethodOne\x12\t.RequestA\x1a\n" +
	".ResponseA\x12\"\n" +
	"\tMethodTwo\x12\t.RequestB\x1a\n" +
	".ResponseB2U\n" +
	"\rSecondService\x12 \n" +
	"\aReverse\x12\n" +
	".ResponseA\x1a\t.RequestA\x12\"\n" +
	"\tTransform\x12\t.RequestB\x1a\n" +
	".ResponseB2;\n" +
	"\fThirdService\x12+\n" +
	"\x0eStreamExchange\x12\t.RequestA\x1a\n" +
	".ResponseA(\x010\x01b\x06proto3"

var (
	file_service_multi_proto_rawDescOnce sync.Once
	file_service_multi_proto_rawDescData []byte
)

func file_service_multi_proto_rawDescGZIP() []byte {
	file_service_multi_proto_rawDescOnce.Do(func() {
		file_service_multi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_multi_proto_rawDesc), len(file_service_multi_proto_rawDesc)))
	})
	return file_service_multi_proto_rawDescData
}

var file_service_multi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_multi_proto_goTypes = []any{
	(*RequestA)(nil),  // 0: RequestA
	(*ResponseA)(nil), // 1: ResponseA
	(*RequestB)(nil),  // 2: RequestB
	(*ResponseB)(nil), // 3: ResponseB
}
var file_service_multi_proto_depIdxs = []int32{
	0, // 0: FirstService.MethodOne:input_type -> RequestA
	2, // 1: FirstService.MethodTwo:input_type -> RequestB
	1, // 2: SecondService.Reverse:input_type -> ResponseA
	2, // 3: SecondService.Transform:input_type -> RequestB
	0, // 4: ThirdService.StreamExchange:input_type -> RequestA
	1, // 5: FirstService.MethodOne:output_type -> ResponseA
	3, // 6: FirstService.MethodTwo:output_type -> ResponseB
	0, // 7: SecondService.Reverse:output_type -> RequestA
	3, // 8: SecondService.Transform:output_type -> ResponseB
	1, // 9: ThirdService.StreamExchange:output_type -> ResponseA
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_multi_proto_init() }
func file_service_multi_proto_init() {
	if File_service_multi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_multi_proto_rawDesc), len(file_service_multi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_service_multi_proto_goTypes,
		DependencyIndexes: file_service_multi_proto_depIdxs,
		MessageInfos:      file_service_multi_proto_msgTypes,
	}.Build()
	File_service_multi_proto = out.File
	file_service_multi_proto_goTypes = nil
	file_service_multi_proto_depIdxs = nil
}
