// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_names.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRequest) Reset() {
	*x = NameRequest{}
	mi := &file_service_names_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRequest) ProtoMessage() {}

func (x *NameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_names_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRequest.ProtoReflect.Descriptor instead.
func (*NameRequest) Descriptor() ([]byte, []int) {
	return file_service_names_proto_rawDescGZIP(), []int{0}
}

func (x *NameRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_service_names_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_names_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_service_names_proto_rawDescGZIP(), []int{1}
}

func (x *NameResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_service_names_proto protoreflect.FileDescriptor

const file_service_names_proto_rawDesc = "" +
	"\n" +
	"\x13service_names.proto\"#\n" +
	"\vNameRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"&\n" +
	"\fNameResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output2\xaa\x02\n" +
	"\rNamingService\x12 \n" +
	"\x01A\x12\f.NameRequest\x1a\r.NameResponse\x12!\n" +
	"\x02AB\x12\f.NameRequest\x1a\r.NameResponse\x12.\n" +
	"\x0fGetHTTPResponse\x12\f.NameRequest\x1a\r.NameResponse\x12+\n" +
	"\fDoXMLParsing\x12\f.NameRequest\x1a\r.NameResponse\x12)\n" +
	"\n" +
	"SimpleCall\x12\f.NameRequest\x1a\r.NameResponse\x12 \n" +
	"\x01X\x12\f.NameRequest\x1a\r.NameResponse\x12*\n" +
	"\vGetUserByID\x12\f.NameRequest\x1a\r.NameResponseb\x06proto3"

var (
	file_service_names_proto_rawDescOnce sync.Once
	file_service_names_proto_rawDescData []byte
)

func file_service_names_proto_rawDescGZIP() []byte {
	file_service_names_proto_rawDescOnce.Do(func() {
		file_service_names_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_names_proto_rawDesc), len(file_service_names_proto_rawDesc)))
	})
	return file_service_names_proto_rawDescData
}

var file_service_names_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_names_proto_goTypes = []any{
	(*NameRequest)(nil),  // 0: NameRequest
	(*NameResponse)(nil), // 1: NameResponse
}
var file_service_names_proto_depIdxs = []int32{
	0, // 0: NamingService.A:input_type -> NameRequest
	0, // 1: NamingService.AB:input_type -> NameRequest
	0, // 2: NamingService.GetHTTPResponse:input_type -> NameRequest
	0, // 3: NamingService.DoXMLParsing:input_type -> NameRequest
	0, // 4: NamingService.SimpleCall:input_type -> NameRequest
	0, // 5: NamingService.X:input_type -> NameRequest
	0, // 6: NamingService.GetUserByID:input_type -> NameRequest
	1, // 7: NamingService.A:output_type -> NameResponse
	1, // 8: NamingService.AB:output_type -> NameResponse
	1, // 9: NamingService.GetHTTPResponse:output_type -> NameResponse
	1, // 10: NamingService.DoXMLParsing:output_type -> NameResponse
	1, // 11: NamingService.SimpleCall:output_type -> NameResponse
	1, // 12: NamingService.X:output_type -> NameResponse
	1, // 13: NamingService.GetUserByID:output_type -> NameResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_names_proto_init() }
func file_service_names_proto_init() {
	if File_service_names_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_names_proto_rawDesc), len(file_service_names_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_names_proto_goTypes,
		DependencyIndexes: file_service_names_proto_depIdxs,
		MessageInfos:      file_service_names_proto_msgTypes,
	}.Build()
	File_service_names_proto = out.File
	file_service_names_proto_goTypes = nil
	file_service_names_proto_depIdxs = nil
}
