// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: text3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextEnum int32

const (
	TextEnum_UNKNOWN TextEnum = 0
	TextEnum_ALPHA   TextEnum = 1
	TextEnum_BETA    TextEnum = 2
)

// Enum value maps for TextEnum.
var (
	TextEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "ALPHA",
		2: "BETA",
	}
	TextEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"ALPHA":   1,
		"BETA":    2,
	}
)

func (x TextEnum) Enum() *TextEnum {
	p := new(TextEnum)
	*p = x
	return p
}

func (x TextEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_text3_proto_enumTypes[0].Descriptor()
}

func (TextEnum) Type() protoreflect.EnumType {
	return &file_text3_proto_enumTypes[0]
}

func (x TextEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextEnum.Descriptor instead.
func (TextEnum) EnumDescriptor() ([]byte, []int) {
	return file_text3_proto_rawDescGZIP(), []int{0}
}

type TextMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active  bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Score   float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Data    []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Status  TextEnum               `protobuf:"varint,6,opt,name=status,proto3,enum=TextEnum" json:"status,omitempty"`
	Sub     *SubMessage            `protobuf:"bytes,7,opt,name=sub,proto3" json:"sub,omitempty"`
	Numbers []int32                `protobuf:"varint,8,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Labels  []string               `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	Counts  map[string]int32       `protobuf:"bytes,10,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TextMessage_Text
	//	*TextMessage_Number
	Payload       isTextMessage_Payload `protobuf_oneof:"payload"`
	Items         []*SubMessage         `protobuf:"bytes,13,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_text3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_text3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_text3_proto_rawDescGZIP(), []int{0}
}

func (x *TextMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TextMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TextMessage) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TextMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TextMessage) GetStatus() TextEnum {
	if x != nil {
		return x.Status
	}
	return TextEnum_UNKNOWN
}

func (x *TextMessage) GetSub() *SubMessage {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *TextMessage) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *TextMessage) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TextMessage) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *TextMessage) GetPayload() isTextMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TextMessage) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*TextMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *TextMessage) GetNumber() int32 {
	if x != nil {
		if x, ok := x.Payload.(*TextMessage_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *TextMessage) GetItems() []*SubMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type isTextMessage_Payload interface {
	isTextMessage_Payload()
}

type TextMessage_Text struct {
	Text string `protobuf:"bytes,11,opt,name=text,proto3,oneof"`
}

type TextMessage_Number struct {
	Number int32 `protobuf:"varint,12,opt,name=number,proto3,oneof"`
}

func (*TextMessage_Text) isTextMessage_Payload() {}

func (*TextMessage_Number) isTextMessage_Payload() {}

type SubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             string                 `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubMessage) Reset() {
	*x = SubMessage{}
	mi := &file_text3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMessage) ProtoMessage() {}

func (x *SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_text3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMessage.ProtoReflect.Descriptor instead.
func (*SubMessage) Descriptor() ([]byte, []int) {
	return file_text3_proto_rawDescGZIP(), []int{1}
}

func (x *SubMessage) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SubMessage) GetY() string {
	if x != nil {
		return x.Y
	}
	return ""
}

var File_text3_proto protoreflect.FileDescriptor

const file_text3_proto_rawDesc = "" +
	"\n" +
	"\vtext3.proto\"\xb2\x03\n" +
	"\vTextMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12!\n" +
	"\x06status\x18\x06 \x01(\x0e2\t.TextEnumR\x06status\x12\x1d\n" +
	"\x03sub\x18\a \x01(\v2\v.SubMessageR\x03sub\x12\x18\n" +
	"\anumbers\x18\b \x03(\x05R\anumbers\x12\x16\n" +
	"\x06labels\x18\t \x03(\tR\x06labels\x120\n" +
	"\x06counts\x18\n" +
	" \x03(\v2\x18.TextMessage.CountsEntryR\x06counts\x12\x14\n" +
	"\x04text\x18\v \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\f \x01(\x05H\x00R\x06number\x12!\n" +
	"\x05items\x18\r \x03(\v2\v.SubMessageR\x05items\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\t\n" +
	"\apayload\"(\n" +
	"\n" +
	"SubMessage\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\tR\x01y*,\n" +
	"\bTextEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ALPHA\x10\x01\x12\b\n" +
	"\x04BETA\x10\x02b\x06proto3"

var (
	file_text3_proto_rawDescOnce sync.Once
	file_text3_proto_rawDescData []byte
)

func file_text3_proto_rawDescGZIP() []byte {
	file_text3_proto_rawDescOnce.Do(func() {
		file_text3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_text3_proto_rawDesc), len(file_text3_proto_rawDesc)))
	})
	return file_text3_proto_rawDescData
}

var file_text3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_text3_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_text3_proto_goTypes = []any{
	(TextEnum)(0),       // 0: TextEnum
	(*TextMessage)(nil), // 1: TextMessage
	(*SubMessage)(nil),  // 2: SubMessage
	nil,                 // 3: TextMessage.CountsEntry
}
var file_text3_proto_depIdxs = []int32{
	0, // 0: TextMessage.status:type_name -> TextEnum
	2, // 1: TextMessage.sub:type_name -> SubMessage
	3, // 2: TextMessage.counts:type_name -> TextMessage.CountsEntry
	2, // 3: TextMessage.items:type_name -> SubMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_text3_proto_init() }
func file_text3_proto_init() {
	if File_text3_proto != nil {
		return
	}
	file_text3_proto_msgTypes[0].OneofWrappers = []any{
		(*TextMessage_Text)(nil),
		(*TextMessage_Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_text3_proto_rawDesc), len(file_text3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_text3_proto_goTypes,
		DependencyIndexes: file_text3_proto_depIdxs,
		EnumInfos:         file_text3_proto_enumTypes,
		MessageInfos:      file_text3_proto_msgTypes,
	}.Build()
	File_text3_proto = out.File
	file_text3_proto_goTypes = nil
	file_text3_proto_depIdxs = nil
}
